name: laserfarm

channels:
  - conda-forge

dependencies:
  - python>=3.10,<3.14
  - pdal
  - python-pdal
  - gdal
  - shapely  # needed to install the correct version of geos
  - pip
  - pip:
      - -r requirements.txt
      - .
